/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_matrice_en_image;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.*;
import java.math.*;
import java.util.ArrayList;
import java.util.Arrays;


/**
 *
 * @author babru
 */
public class Affichage extends javax.swing.JFrame {
    /**
     * Creates new form Affichage
     */
    public Affichage() {
        System.out.println("y");
        initComponents();
        Base_image base_image = new Base_image();
        Base_chiffre base_chiffre = new Base_chiffre();
        int n = 613; 
            try { //int [] image = base.traiter(12700);
                
            Image image_a_modifier = new Image(base_image.traiter(n));
            image_a_modifier.modifier();
            monpanel1.setImage(image_a_modifier);
            base_chiffre.traiter(n);
            }
            catch (Exception e) {
                e.printStackTrace();
            }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monpanel1 = new projet_matrice_en_image.Monpanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        
            
            
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Affichage().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projet_matrice_en_image.Monpanel monpanel1;
    // End of variables declaration//GEN-END:variables
}
